### ISSUE TITLE
[Feature Request] Automatically Tag?

### ISSUE THREAD

**Issue by eiiot** [edward-shen/shlink#2]
Would it be possible to automatically tag generated URLs with "Extension" or something? Just so I can sort through and delete just those URLs later

**Comment by edward-shen** [comment]
Thanks for the feature request. I've added support for this; you're now able toggle the option for the extension to automatically tag the link it creates in the latest version, 0.4.2.

0.4.2 has been submitted for review; I'll let you know when it's been published on both Firefox and Chrome web stores.

**Comment by eiiot** [comment]
That was incredibly fast! Thanks so much :)

**Comment by edward-shen** [comment]
Looks like the new version is on both app stores now. You may need to manually check for updates. Feel free to re-open or create a new issue if you have any problems!
